export const initialData = {
  movie_id: 1,
  movie_version_id: 1,
  showtimes: [
    {
      date: "2025-04-01",
      room_id: 1,
      cinema_id: 1,
      showtimes: [
        {
          start_time: "12:00",
          end_time: "13:15",
          type: "existing",
          overlapping: false,
          booked: false,
        },
        {
          start_time: "15:00",
          end_time: "16:15",
          type: "existing",
          overlapping: false,
          booked: false,
        },
        {
          start_time: "08:00",
          end_time: "09:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "09:15",
          end_time: "10:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "10:30",
          end_time: "11:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "11:45",
          end_time: "13:00",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "13:00",
          end_time: "14:15",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "14:15",
          end_time: "15:30",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "15:30",
          end_time: "16:45",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "16:45",
          end_time: "18:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "18:00",
          end_time: "19:15",
          type: "generated",
          overlapping: false,
        },
      ],
    },
    {
      date: "2025-04-01",
      room_id: 3,
      cinema_id: 2,
      showtimes: [
        {
          start_time: "12:00",
          end_time: "13:15",
          type: "existing",
          overlapping: false,
          booked: false,
        },
        {
          start_time: "15:00",
          end_time: "16:15",
          type: "existing",
          overlapping: false,
          booked: false,
        },
        {
          start_time: "08:00",
          end_time: "09:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "09:15",
          end_time: "10:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "10:30",
          end_time: "11:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "11:45",
          end_time: "13:00",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "13:00",
          end_time: "14:15",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "14:15",
          end_time: "15:30",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "15:30",
          end_time: "16:45",
          type: "generated",
          overlapping: true,
        },
        {
          start_time: "16:45",
          end_time: "18:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "18:00",
          end_time: "19:15",
          type: "generated",
          overlapping: false,
        },
      ],
    },
    {
      date: "2025-04-03",
      room_id: 1,
      cinema_id: 1,
      showtimes: [
        {
          start_time: "08:00",
          end_time: "09:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "09:15",
          end_time: "10:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "10:30",
          end_time: "11:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "11:45",
          end_time: "13:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "13:00",
          end_time: "14:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "14:15",
          end_time: "15:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "15:30",
          end_time: "16:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "16:45",
          end_time: "18:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "18:00",
          end_time: "19:15",
          type: "generated",
          overlapping: false,
        },
      ],
    },
    {
      date: "2025-04-03",
      room_id: 3,
      cinema_id: 2,
      showtimes: [
        {
          start_time: "08:00",
          end_time: "09:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "09:15",
          end_time: "10:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "10:30",
          end_time: "11:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "11:45",
          end_time: "13:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "13:00",
          end_time: "14:15",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "14:15",
          end_time: "15:30",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "15:30",
          end_time: "16:45",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "16:45",
          end_time: "18:00",
          type: "generated",
          overlapping: false,
        },
        {
          start_time: "18:00",
          end_time: "19:15",
          type: "generated",
          overlapping: false,
        },
      ],
    },
  ],
};
